### ISSUE TITLE
Distinguish Test and Repairs on Large Meters

### ISSUE THREAD

**Issue by JMurk** [JMurk/COB_Cityworks_Tasks#13]
Per Cynthia Spence:

We are trying to establish a way to distinguish Large Meter Testing from Large Meter Replacement.

We can keep the Large Meter Repair/Replace WO Type, but can we add a Custom Field that can identify if the WO was Test Only, Test and Repair, or Test and Replace?

**Comment by JMurk** [comment]
Discussed with Cynthia on the phone 4/21:

Add a new Custom Field Category for the Large Meter Repair/Replace WO:

-Test Date
-Test Result (Pass, Fail)
-Work Type (Test Only, Test & Repair, Test and Replace)

**Comment by JMurk** [comment]
Complete in Test, Email Cynthia for feedback/approval

**Comment by pbhattarai** [comment]
Task completed in Production on May 2, 2017. No issues or concern reported by Cynthia.
