### ISSUE TITLE
Inlet Cleaning - Adjust Map Services

### ISSUE THREAD

**Issue by JMurk** [JMurk/COB_Cityworks_Tasks#14]
- Add Neighborhoods

- Add Street Sweeping routes

- Resymbolize modified inlets

-Inlets inspected w/in the last 30 days
-Inlets cleaned w/in the last 30 days

**Comment by pbhattarai** [comment]
SW@SDE@default.sde\sw.DBO.SDIC\sw.DBO.SDInletCleaning
S:\Transition\DB_Connections (1)\SW@SDE@default.sde\sw.DBO.SDInlet_Inspection

Street sweeping route also at SW@SDE@default.sde\sw.DBO.SDIC

**Comment by JMurk** [comment]
All of the above added in the "Inlet Inspection" Service Group in test.
