### ISSUE TITLE
Create Scripts to Update Users for AD Implementation

### ISSUE THREAD

**Issue by JMurk** [JMurk/COB_Cityworks_Tasks#18]
Create update scripts:

•	Employee.LoginName = “city username” (e.g. joe.murk).
•	CWSVRUSER.username, CWSVRUSER.loweredusername = “domain\city username” (e.g. Baltimore\joe.murk)

@pbhattarai to send spreadsheet for AD>CW mapping

**Comment by pbhattarai** [comment]
sent AD-CW mapping table to @JMurk

**Comment by JMurk** [comment]
Scripts created and executed on 5/26.
