### ISSUE TITLE
Remove some fields from Create WO 

### ISSUE THREAD

**Issue by pbhattarai** [JMurk/COB_Cityworks_Tasks#35]
While trying to mimic workflow for CSSD, starting from GIS search followed by Create WO. Some of the new fields in newer version might need to be removed, especially those that were not present in old version and don't serve much purpose (and only distract users).

![image](https://user-images.githubusercontent.com/9613673/29463656-727e77b0-8401-11e7-9e18-98b9fc1e3151.png)

**Comment by JMurk** [comment]
Determined to be an unnecessary change.
