### ISSUE TITLE
SR Data Updates for Investigator App Use

### ISSUE THREAD

**Issue by JMurk** [JMurk/COB_Cityworks_Tasks#5]

**Comment by JMurk** [comment]
Updated SRs provided by Bharat on 4/6/17 to populate the DATEINVTDONE and set FIELDINVTDONE (Investigation checkbox) = 'Y"

@Bharat2331 please verify that the mobile app is ready for investigators to use.

**Comment by Bharat2331** [comment]
once comments and attachment are added it does not allow to modify even before confirming the transaction. What if an investigator enter the comments in error!

**Comment by JMurk** [comment]
This functions the same as Desktop... Once you save, you cannot delete.  Proofread!
